[package]
name = "flutter_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"

nipaplay-next = { path = "../nipaplay-next" }
once_cell = { workspace = true }
log = { workspace = true }
